### ISSUE TITLE
Building with Qt5.6

### ISSUE THREAD

**Issue by kheaactua** [MASKOR/Qt3DPointcloudRenderer#1]
Can this work with Qt5.6?

I get `Qt3DPointcloudRenderer/src/qpointcloudgeometry.cpp:4:10: fatal error: 'Qt3DRender/qbufferdatagenerator.h' file not found`

When I googled it though, I found [an issue](https://codereview.qt-project.org/#/c/151076/) about that file having been called `qbufferfunctor.h` in the past, but I'm not familiar with Qt to know if I can just symlink that file to the new name?

**Comment by dabulla** [comment]
It worked with Qt5.6 at commit 9d1a289068f7178173b6ea2e191ab5ee1e54c07a.

There have been minor bugfixes since then (shader attribute names of normals and intensity were wrong).
I think you could also rename the class from *DataGenerator back to *BufferFunctor as seen in this diff:
https://github.com/MASKOR/Qt3DPointcloudRenderer/commit/25f8cf1cd5e93daebb36956d6388d20538df4173

Nevertheless I would recommend to always use the newest version of Qt3D!

**Comment by kheaactua** [comment]
Sounds good, I'll give it a try.  Thanks.

My work said I could only upgrade to the latest LTS version of Qt, which is 5.6..

**Comment by efra-mx** [comment]
Hi,

I am trying your code in my project but I get some errors during linking time:

`qt_point_cloud_viewer.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QPointfield::staticMetaObject" (?staticMetaObject@QPointfield@@2UQMetaObject@@B)
4>qt_point_cloud_viewer.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QPointcloud::staticMetaObject" (?staticMetaObject@QPointcloud@@2UQMetaObject@@B)
4>qt_point_cloud_viewer.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QPointcloudGeometry::staticMetaObject" (?staticMetaObject@QPointcloudGeometry@@2UQMetaObject@@B)
4>qt_point_cloud_viewer.obj : error LNK2001: unresolved external symbol "public: static struct QMetaObject const QPointCloudReader::staticMetaObject" (?staticMetaObject@QPointCloudReader@@2UQMetaObject@@B)
4`

What is the purpose of this command?
`execute_process(
  COMMAND "${CMAKE_COMMAND}" "-E" "create_symlink" ${CMAKE_CURRENT_SOURCE_DIR}/data ${CMAKE_BINARY_DIR}/example/data
)`

I am using PCL 1.8.0 and Qt 5.7.

Notice that I have renamed the files and the headers location, but nothing functional.
Thank you very much!!

**Comment by dabulla** [comment]
This indicates a problem with moc. It may helps to clean and rebuild the project. CMake did not recognize that the classes derive from QObject and have a Q_OBJECT macro. Don't forget to `set(CMAKE_AUTOMOC ON)` in your CMake. More solutions to this problem are discussed here http://stackoverflow.com/questions/14170770/unresolved-external-symbol-public-virtual-struct-qmetaobject-const-thiscal

The "create_symlink" line links the "data" folder from your sources to the binary folder, so the example can find the bunny-pointcloud at "data/bunny.pcd".

You can also easily add all files to a qmake project. This may be more appropriate for a pure qt extension and I might switch in the future.

**Comment by efra-mx** [comment]
Thanks.
the issue was actually beacuase  dllexport was missing
